### ISSUE TITLE
popup is unreadable if response from gpt-3 is too long.

### ISSUE THREAD

**Issue by mosfetti** [Arrendy/gpt3-vscode-extension#23]
so I just made a request which had a very long output, and the popup was going off screen.
Not being able to copy output, so basically I just lost tokens.

Output to a txt file or an UI fix would be appreciated.

**Comment by MikeBirdTech** [comment]
UI options are quite limited due to VS Code. I've explored the different information messages options and found the modal to be the most capable. Have you seen any other extensions that handle this better? I'd love to find a better UI option.

I don't mind the idea of being able to output to a txt file but the majority of completions aren't going to require that and it is worse UX than the modal. Maybe if there's a character count cutoff that will output to txt? Any other ideas?

Also, what length of response caused the issue? I was able to copy the output in its entirety even when it overflowed the modal but I wasn't pushing the 4k token limit. 

Also curious what you've set your `maxTokens` and `codeMaxTokens` values to.

Thanks!
